<a href="https://colab.research.google.com/github/yimstar9/Engineer-Big-Data-Analysis_R/blob/main/3%ED%9A%8C%EC%9E%91%EC%97%85%ED%98%952_%EA%B8%B0%EC%B6%9C_%EC%9C%A0%ED%98%95(%EC%8B%AC%ED%99%94)%C2%B6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# 작업형2 기출 유형(심화)¶
# 본 문제는 변형한 심화 문제 입니다.
# 오리지널 3회 기출 유형을 보고 싶은 분은 아래 클래스-커리큘럼 탭에 무료공개
# (3회 작업형2)로 영상과 데이터셋을 올려놨어요!
# https://class101.net/products/467P0ZPH0lVX9FwFBDz7
# 여행 보험 패키지 상품을 구매할 확률 값을 구하시오
# 예측할 값(y): TravelInsurance (여행보험 패지지를 구매 했는지 여부 0:구매안함, 1:구매)
# 평가: roc-auc 평가지표
# data: t2-1-train.csv, t2-1-test.csv

######################## 제출 형식#########################
# id,TravelInsurance
# 0,0.3
# 1,0.48
# 2,0.3
# 3,0.83

# Baseline
# 3회 기출문제에서 데이터 셋을 편집해 조금 더 어렵게 만들었어요
# 결측치 추가
# Employment Type 컬럼에 카테고리 추가
# sample_submission 파일은 제공된 적 없음(3회 때 제출 형식에 대한 이슈가 있어 
# 제공하거나 제출 형식을 명확하게 설명할 가능성 있어 보임)
# 데이터셋 https://www.kaggle.com/competitions/big-data-analytics-certification/data?select=t2-1-test.csv
# 데이터셋 https://www.kaggle.com/competitions/big-data-analytics-certification/data?select=t2-1-train.csv
train <- read.csv("t2-1-train.csv",header=T)
test <- read.csv("t2-1-test.csv",header=T)
#install.packages("c:\\randomForest_4.6-14.tar.gz",repos=NULL,type="source")
#install.packages("randomForest")
#install.packages("caret")
library(caret)
library(randomForest)
library(ModelMetrics)
#결측치 확인, factor 변환
train$Employment.Type<-as.factor(train$Employment.Type)
train$GraduateOrNot<-as.factor(train$GraduateOrNot)
train$FrequentFlyer <- as.factor(train$FrequentFlyer)
train$EverTravelledAbroad <- as.factor(train$EverTravelledAbroad)
train$TravelInsurance <- as.factor(train$TravelInsurance)
colSums(is.na(train))
train$AnnualIncome <- ifelse(is.na(train$AnnualIncome),0,train$AnnualIncome)

idx<-sample(1:nrow(train),nrow(train)*0.7)
dftrain <- train[idx,]
dftest <- train[-idx,]

m <- randomForest(TravelInsurance~.-(id),data=dftrain,ntree=100)
p <- predict(m,newdata=dftest,type="response")

#F1-score
caret::confusionMatrix(dftest$TravelInsurance, p)$byClass[7]


# Accuracy
caret::confusionMatrix(dftest$TravelInsurance, p)$overall[1]

#ROC auc
auc(dftest$TravelInsurance, p) #랜덤포레스트


 test$Employment.Type<-as.factor(test$Employment.Type)
 test$GraduateOrNot<-as.factor(test$GraduateOrNot)
 test$FrequentFlyer <- as.factor(test$FrequentFlyer)
 test$EverTravelledAbroad <- as.factor(test$EverTravelledAbroad)
 test$AnnualIncome <- as.numeric(test$AnnualIncome)
# str(test)
# str(dftest)
# str(m2)
sapply(train, levels)
sapply(test, levels)
levels(train$Employment.Type) <-  levels(test$Employment.Type)
# nrow(test)
# str(test)
# nrow(p2)
m2 <- randomForest(TravelInsurance~.-c(id), data=train, ntree=100)
p2 <- predict(m2, test,type="prob")


a <- as.character(test$id)
b <- as.character(p2[,1])
c<-data.frame(ID=a,Pro=b)

write.csv(c, "travelInsurance.csv", row.names = F)
abc<-read.csv("travelInsurance.csv")
head(abc)

                 id                 Age     Employment.Type       GraduateOrNot
                  0                   0                   0                   0
       AnnualIncome       FamilyMembers     ChronicDiseases       FrequentFlyer
                  4                   0                   0                   0
EverTravelledAbroad     TravelInsurance
                  0                   0

       F1
0.8864697

Accuracy
0.836689

[1] 0.7753092

$id
NULL

$Age
NULL

$Employment.Type
[1] "Government Sector"            "Private Sector/Self Employed"

$GraduateOrNot
[1] "No"  "Yes"

$AnnualIncome
NULL

$FamilyMembers
NULL

$ChronicDiseases
NULL

$FrequentFlyer
[1] "No"  "Yes"

$EverTravelledAbroad
[1] "No"  "Yes"

$TravelInsurance
[1] "0" "1"

$id
NULL

$Age
NULL

$Employment.Type
[1] "Casual employment"            "Government Sector"
[3] "Private Sector/Self Employed"

$GraduateOrNot
[1] "No"  "Yes"

$AnnualIncome
NULL

$FamilyMembers
NULL

$ChronicDiseases
NULL

$FrequentFlyer
[1] "No"  "Yes"

$EverTravelledAbroad
[1] "No"  "Yes"

  ID Pro
1 0  0.79
2 1  0.7
3 2  0.84
4 3  0.19
5 4  0.73
6 5  0.19

    ID  Pro
1    0  0.79
2    1  0.70
3    2  0.84
4    3  0.19
5    4  0.73
6    5  0.19
7    6  0.47
8    7  0.77
9    8  0.23
10   9  0.82
11  10  0.53
12  11  0.77
13  12  0.68
14  13  0.65
15  14  0.24
16  15  0.70
17  16  0.75
18  17  0.69
19  18  0.83
20  19  0.78
21  20    NA
22  21  0.77
23  22  0.40
24  23  0.19
25  24  0.77
26  25  0.23
27  26  0.24
28  27  0.87
29  28  0.18
30  29  0.24
⋮   ⋮   ⋮
468 467 0.20
469 468 0.52
470 469 0.68
471 470 0.67
472 471 0.66
473 472 0.79
474 473 0.82
475 474 0.22
476 475 0.70
477 476 0.53
478 477 0.66
479 478 0.33
480 479 0.79
481 480 0.34
482 481 0.66
483 482 0.62
484 483 0.71
485 484 0.23
486 485 0.80
487 486 0.88
488 487 0.73
489 488 0.77
490 489 0.20
491 490 0.55
492 491 0.77
493 492 0.78
494 493 0.21
495 494 0.78
496 495 0.26
497 496 0.12